language: php
php:
  - '7.0'
  - '7.1'
  - '7.2'

env:
    - ELASTICA_VERSION=^5.0
    - ELASTICA_VERSION=^6.0

before_script:
    - composer self-update
    - composer require ruflin/elastica:${ELASTICA_VERSION} --no-update
    - composer update

script:
    - vendor/bin/phpunit --coverage-clover=coverage.clover

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
    - bash <(curl -s https://codecov.io/bash)
